steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/stripe-prototype:${SHORT_SHA}",
        "-t",
        "gcr.io/$PROJECT_ID/stripe-prototype:${BRANCH_NAME}",
        "--build-arg",
        "COMMIT_SHA=${SHORT_SHA}",
        "--build-arg",
        "BRANCH_NAME=${BRANCH_NAME}",
        ".",
        ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stripe-prototype"]
